# Generated by Django 3.2 on 2024-06-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipoProducto', '0003_alter_tipoproducto_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='identificacion',
            field=models.CharField(max_length=50, verbose_name='id Tipo de producto'),
        ),
    ]
