# Generated by Django 3.2 on 2024-06-13 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipoProducto', '0006_alter_tipoproducto_identificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoproducto',
            name='identificacion',
        ),
    ]
