# Generated by Django 3.2 on 2024-06-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipoProducto', '0007_remove_tipoproducto_identificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoproducto',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
