# Generated by Django 3.2 on 2024-06-17 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipoProducto', '0008_rename_nombre_tipoproducto_nombres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoproducto',
            old_name='nombres',
            new_name='nombre',
        ),
    ]
