# Generated by Django 3.2 on 2024-06-10 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipoProducto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Dato Adicional')),
            ],
            options={
                'verbose_name': 'Adicional',
                'verbose_name_plural': 'Adicionales',
            },
        ),
        migrations.CreateModel(
            name='datoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_datoProducto', models.CharField(max_length=50, verbose_name='ID de producto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de producto')),
                ('precio', models.CharField(max_length=50, verbose_name='Precio de producto')),
                ('stock', models.CharField(max_length=50, verbose_name='Cantidad en stock')),
                ('datosAdicionales', models.ManyToManyField(to='datoProducto.Adicionales')),
                ('id_tipoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipoProducto.tipoproducto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
