# Generated by Django 3.2 on 2024-06-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datoProducto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoproducto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de producto'),
        ),
        migrations.AlterField(
            model_name='datoproducto',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Cantidad en stock'),
        ),
    ]
