# Generated by Django 3.2 on 2024-06-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datoProducto', '0002_auto_20240610_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datoproducto',
            name='id_datoProducto',
        ),
    ]
