# Generated by Django 3.2 on 2024-06-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datoProducto', '0004_auto_20240612_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoproducto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Precio de producto'),
        ),
        migrations.AlterField(
            model_name='datoproducto',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Cantidad en stock'),
        ),
    ]
