# Generated by Django 3.2 on 2024-06-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datoProducto', '0009_datoproducto_nombre_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoproducto',
            name='producto',
            field=models.ImageField(blank=True, upload_to='datoProducto', verbose_name='Imagen'),
        ),
    ]
